name: "Setup and install"
description: "Common setup steps for Actions"

inputs:
  node-version:
    description: "Node.js version"
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"

    - name: Install dependencies
      shell: bash
      run: npm install --frozen-lockfile
