import { Quicksand, Nunito } from "next/font/google";

import { Header } from "@/components/Header/Header";
import { WebVitals } from "@/components/WebVitals";

import type { Metadata } from "next";

import "./globals.css";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} ${nunito.variable} antialiased bg-[#FAF9F6]`}
      >
        {/* Skip navigation link for accessibility */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-[60] focus:px-4 focus:py-2 focus:bg-white focus:text-black focus:rounded-md focus:outline-none focus:ring-2 focus:ring-pink-500"
        >
          Skip to main content
        </a>
        <Header />
        <WebVitals />
        <main id="main-content">{children}</main>
      </body>
    </html>
  );
}
